services:
  postgres-db:
    image: postgres:16
    container_name: postgresql_hotels
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: hotels
    ports:
      - 5434:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
